const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const { asyncHandler } = require('../middleware/errorHandler');

/**
 * @route   POST /api/pdf/generate
 * @desc    Generate PDF from form data
 * @access  Public
 */
router.post('/generate', asyncHandler(async (req, res) => {
    const { data, template, options } = req.body;

    if (!data) {
        return res.status(400).json({
            success: false,
            error: 'Data is required for PDF generation'
        });
    }

    try {
        const pdfBuffer = await generatePDF(data, template || 'default', options || {});

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', 'attachment; filename="document.pdf"');
        res.setHeader('Content-Length', pdfBuffer.length);
        
        res.send(pdfBuffer);
    } catch (error) {
        res.status(500).json({
            success: false,
            error: `Failed to generate PDF: ${error.message}`
        });
    }
}));

/**
 * Generate PDF document
 */
async function generatePDF(data, template, options) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: options.size || 'A4',
                margins: {
                    top: 50,
                    bottom: 50,
                    left: 50,
                    right: 50
                }
            });

            const buffers = [];
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => {
                const pdfData = Buffer.concat(buffers);
                resolve(pdfData);
            });

            // Generate content based on template
            switch (template) {
                case 'submission':
                    generateSubmissionPDF(doc, data, options);
                    break;
                case 'invoice':
                    generateInvoicePDF(doc, data, options);
                    break;
                case 'report':
                    generateReportPDF(doc, data, options);
                    break;
                default:
                    generateDefaultPDF(doc, data, options);
            }

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
}

/**
 * Generate submission PDF
 */
function generateSubmissionPDF(doc, data, options) {
    // Header
    doc.fontSize(20).text('Form Submission', { align: 'center' });
    doc.moveDown();

    // Submission info
    doc.fontSize(12)
       .text(`Submission Date: ${new Date().toLocaleDateString()}`)
       .text(`Submission ID: ${data.submissionId || 'N/A'}`)
       .moveDown();

    // Form data
    doc.fontSize(14).text('Submitted Information:', { underline: true });
    doc.moveDown(0.5);

    Object.entries(data).forEach(([key, value]) => {
        if (key !== 'submissionId' && value) {
            const label = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
            doc.fontSize(12)
               .text(`${label}: `, { continued: true })
               .text(Array.isArray(value) ? value.join(', ') : value.toString());
        }
    });

    // Footer
    doc.moveDown(2);
    doc.fontSize(10)
       .text('Generated by AI Micro App Builder', { align: 'center' })
       .text(`Generated on: ${new Date().toLocaleString()}`, { align: 'center' });
}

/**
 * Generate default PDF
 */
function generateDefaultPDF(doc, data, options) {
    doc.fontSize(18).text('Document', { align: 'center' });
    doc.moveDown();

    doc.fontSize(12).text(JSON.stringify(data, null, 2));
}

module.exports = router;